version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      lifecycle:
        patterns:
          - "androidx.lifecycle:*"
      kotlin-toolchain:
        patterns:
          - "org.jetbrains.kotlin*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
